version: '3.8'

services:
  redis:
    image: redis:7.0.11-alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server
    restart: unless-stopped
    tty: true

volumes:
  redis_data: